// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/services/statsservice/statsservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.com/emixam23/fizz-and-buzz/internal/domain/models"
	reflect "reflect"
)

// MockIStatsService is a mock of IStatsService interface
type MockIStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockIStatsServiceMockRecorder
}

// MockIStatsServiceMockRecorder is the mock recorder for MockIStatsService
type MockIStatsServiceMockRecorder struct {
	mock *MockIStatsService
}

// NewMockIStatsService creates a new mock instance
func NewMockIStatsService(ctrl *gomock.Controller) *MockIStatsService {
	mock := &MockIStatsService{ctrl: ctrl}
	mock.recorder = &MockIStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIStatsService) EXPECT() *MockIStatsServiceMockRecorder {
	return m.recorder
}

// GetFnbRequestsInputsStats mocks base method
func (m *MockIStatsService) GetFnbRequestsInputsStats(sorted bool) ([]*models.FnbRequestInputStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFnbRequestsInputsStats", sorted)
	ret0, _ := ret[0].([]*models.FnbRequestInputStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFnbRequestsInputsStats indicates an expected call of GetFnbRequestsInputsStats
func (mr *MockIStatsServiceMockRecorder) GetFnbRequestsInputsStats(sorted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFnbRequestsInputsStats", reflect.TypeOf((*MockIStatsService)(nil).GetFnbRequestsInputsStats), sorted)
}

// GetFnbRequestsMostUsedCombination mocks base method
func (m *MockIStatsService) GetFnbRequestsMostUsedCombination() (*models.FnbRequestInputStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFnbRequestsMostUsedCombination")
	ret0, _ := ret[0].(*models.FnbRequestInputStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFnbRequestsMostUsedCombination indicates an expected call of GetFnbRequestsMostUsedCombination
func (mr *MockIStatsServiceMockRecorder) GetFnbRequestsMostUsedCombination() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFnbRequestsMostUsedCombination", reflect.TypeOf((*MockIStatsService)(nil).GetFnbRequestsMostUsedCombination))
}
