// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/services/fnbservice/fnbservice.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "gitlab.com/emixam23/fizz-and-buzz/internal/domain/models"
	reflect "reflect"
)

// MockIFnbService is a mock of IFnbService interface
type MockIFnbService struct {
	ctrl     *gomock.Controller
	recorder *MockIFnbServiceMockRecorder
}

// MockIFnbServiceMockRecorder is the mock recorder for MockIFnbService
type MockIFnbServiceMockRecorder struct {
	mock *MockIFnbService
}

// NewMockIFnbService creates a new mock instance
func NewMockIFnbService(ctrl *gomock.Controller) *MockIFnbService {
	mock := &MockIFnbService{ctrl: ctrl}
	mock.recorder = &MockIFnbServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIFnbService) EXPECT() *MockIFnbServiceMockRecorder {
	return m.recorder
}

// GetFizzAndBuzz mocks base method
func (m *MockIFnbService) GetFizzAndBuzz(m1 uint32, s1 string, m2 uint32, s2 string, limit uint64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFizzAndBuzz", m1, s1, m2, s2, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFizzAndBuzz indicates an expected call of GetFizzAndBuzz
func (mr *MockIFnbServiceMockRecorder) GetFizzAndBuzz(m1, s1, m2, s2, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFizzAndBuzz", reflect.TypeOf((*MockIFnbService)(nil).GetFizzAndBuzz), m1, s1, m2, s2, limit)
}

// GetFnbRequestsHistory mocks base method
func (m *MockIFnbService) GetFnbRequestsHistory(limit *uint64) ([]*models.FnbRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFnbRequestsHistory", limit)
	ret0, _ := ret[0].([]*models.FnbRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFnbRequestsHistory indicates an expected call of GetFnbRequestsHistory
func (mr *MockIFnbServiceMockRecorder) GetFnbRequestsHistory(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFnbRequestsHistory", reflect.TypeOf((*MockIFnbService)(nil).GetFnbRequestsHistory), limit)
}
