CREATE TABLE IF NOT EXISTS fnb_requests (
    id SERIAL PRIMARY KEY,
    request_date TIMESTAMP NOT NULL,
    n1 BIGSERIAL NOT NULL,
    s1 TEXT NOT NULL,
    n2 BIGSERIAL NOT NULL,
    s2 TEXT NOT NULL,
    rlimit BIGSERIAL NOT NULL
);
